### ISSUE TITLE
Nouvelle URL

### ISSUE THREAD

**Issue by BoboTiG** [Oros42/find_shaarlis#2]
Salut,

Je voulais faire une PR pour spécifier ma nouvelle URL (après presque 1 an HS) mais finalement je ne sais pas s'il faut modifier `filter.php`.

L'ancienne URL est `https://tiger-222.fr/shaarli/?do=rss` et la nouvelle `http://www.tiger-222.fr/links/?do=rss`.

Dois-je faire quelque chose en particulier ?

**Comment by Oros42** [comment]
Salut :-)

Il suffisait simplement de me signaler le changement d'URL ^_^
J'ai mis à jour la liste https://github.com/Oros42/shaarlis_list
Ton shaarli ne devrait pas tarder à apparaître sur ma river https://ecirtam.net/shaarlirss/

A+ ;-)
